export const BlogCardData = [
  {
    title: "Apps Developed Using Llama & Together AI",
    description: "Explore a collection of applications built using Llama and Together AI, showcasing different capabilities from utility tools to productivity applications.",
    date: "2024-02-20",
    tags: ["ai", "development", "llama", "together-ai"],
    slug: "apps-with-llama-and-together",
    readTime: "5 min read"
  },
  {
    date: "2024-02-15",
    id: "what-is-agentic-rag",
    publishedAt: "2024-02-15T00:00:00.000Z",
    slug: "what-is-agentic-rag",
    tags: ["ai", "rag", "agents", "llm"],
    title: "What is Agentic RAG",
    updatedAt: "2024-02-15T00:00:00.000Z",
    description: "Explore how Agentic RAG enhances traditional RAG pipelines with AI agents, enabling more powerful and versatile LLM-powered applications.",
    views: 0,
    image: null,
  },
  {
    date: "2024-02-10",
    id: "future-of-ai-agents",
    publishedAt: "2024-02-10T00:00:00.000Z",
    slug: "future-of-ai-agents",
    tags: ["ai", "future-tech", "innovation"],
    title: "The Future of AI Agents",
    updatedAt: "2024-02-10T00:00:00.000Z",
    description: "Explore the future possibilities of AI agents and their potential impact on various industries. Discover emerging trends and preparations needed.",
    views: 0,
    image: null,
  },
  {
    date: "2024-02-05",
    id: "ai-agents-for-data-analysis",
    publishedAt: "2024-02-05T00:00:00.000Z",
    slug: "ai-agents-for-data-analysis",
    tags: ["ai", "data-analysis", "automation"],
    title: "AI Agents for Data Analysis",
    updatedAt: "2024-02-05T00:00:00.000Z",
    description: "Learn how to leverage AI agents for powerful data analysis and insights generation. Discover automated approaches to data processing.",
    views: 0,
    image: null,
  },
  {
    date: "2024-01-30",
    id: "ai-agents-for-code-generation",
    publishedAt: "2024-01-30T00:00:00.000Z",
    slug: "ai-agents-for-code-generation",
    tags: ["ai", "coding", "automation"],
    title: "AI Agents for Code Generation",
    updatedAt: "2024-01-30T00:00:00.000Z",
    description: "Explore how AI agents are revolutionizing code generation and development workflows. Learn to leverage AI for better coding productivity.",
    views: 0,
    image: null,
  },
  {
    date: "2024-01-25",
    id: "ai-agents-in-customer-service",
    publishedAt: "2024-01-25T00:00:00.000Z",
    slug: "ai-agents-in-customer-service",
    tags: ["ai", "customer-service", "automation"],
    title: "AI Agents in Customer Service",
    updatedAt: "2024-01-25T00:00:00.000Z",
    description: "Discover how AI agents are transforming customer service and support operations. Learn implementation strategies and best practices.",
    views: 0,
    image: null,
  },
  {
    date: "2024-01-20",
    id: "building-ai-agents-for-productivity",
    publishedAt: "2024-01-20T00:00:00.000Z",
    slug: "building-ai-agents-for-productivity",
    tags: ["ai", "productivity", "automation"],
    title: "Building AI Agents for Productivity",
    updatedAt: "2024-01-20T00:00:00.000Z",
    description: "Learn how to create and deploy AI agents that can boost your productivity and automate repetitive tasks.",
    views: 0,
    image: null,
  },
  {
    date: "2024-01-15",
    id: "building-apps-with-no-code-tools",
    publishedAt: "2024-01-15T00:00:00.000Z",
    slug: "building-apps-with-no-code-tools",
    tags: ["no-code", "development", "tools"],
    title: "Building Apps with No-Code Tools",
    updatedAt: "2024-01-15T00:00:00.000Z",
    description: "Explore how to create powerful applications without writing traditional code. Learn about the best no-code tools and how to leverage them for rapid development.",
    views: 0,
    image: null,
  },
  {
    date: "2024-01-10",
    id: "power-of-free-development-tools",
    publishedAt: "2024-01-10T00:00:00.000Z",
    slug: "power-of-free-development-tools",
    tags: ["tools", "development", "free"],
    title: "The Power of Free Development Tools",
    updatedAt: "2024-01-10T00:00:00.000Z",
    description: "A comprehensive guide to the best free tools for modern app development. Discover how to build professional applications without breaking the bank.",
    views: 0,
    image: null,
  },
  {
    date: "2024-01-05",
    id: "automating-your-workflow",
    publishedAt: "2024-01-05T00:00:00.000Z",
    slug: "automating-your-workflow",
    tags: ["automation", "workflow", "productivity"],
    title: "Automating Your Workflow",
    updatedAt: "2024-01-05T00:00:00.000Z",
    description: "Learn how to automate repetitive tasks and boost your productivity. Step-by-step guide to creating efficient workflows.",
    views: 0,
    image: null,
  }
];
